name: Fuzzing
on: [pull_request]
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  # Run all fuzzing tests. Some of them use Go 1.18's testing.F.
  # Others use https://github.com/AdaLogics/go-fuzz-headers.
  ci_fuzz:
    name: CI Fuzz
    if: github.repository == 'containerd/containerd'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@037a2b0dbcc9402512c06805ad06637c6003bf79 # master
      with:
        oss-fuzz-project-name: 'containerd'
        language: go
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@037a2b0dbcc9402512c06805ad06637c6003bf79 # master
      with:
        oss-fuzz-project-name: 'containerd'
        fuzz-seconds: 300
        language: go
      continue-on-error: true
    - name: Upload Crash
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts

  # Make sure all fuzzing tests which use Go 1.18's testing.F are
  # runnable with go test -fuzz.
  go_test_fuzz:
    name : go test -fuzz
    if: github.repository == 'containerd/containerd'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ./.github/actions/install-go
      - run: script/go-test-fuzz.sh
